#!/bin/bash
ESC=$(printf '\033')

read -p "${ESC}[1;39mPress set username: ${ESC}[m" username
printf "${ESC}[1;35mEntered username: ${username}${ESC}[m\n"
while :
do
	read -p "${ESC}[1;39mPress set github URL: ${ESC}[m" url
	printf "${ESC}[1;35mEntered url: $url${ESC}[m\n"
	if [[ ${url} =~ ^https://github.com/.+\.git$ ]]; then
		break
	else
		printf "${ESC}[1;31mError : Please Input 'https://github.com/sample/sample.git' URL format${ESC}[m\n"
	fi
done

read -sp "${ESC}[1;39mPress set token: ${ESC}[m" token
printf "${ESC}[1;35mEntered token: *****[m\n"

git remote set-url origin "https://${username}:${token}@github.com${url:18}"
printf "\n${ESC}[1;36morigin set : https://${username}:token@github.com${url:18}${ESC}[m\n"
