#!/bin/bash

sudo apt update
sudo apt upgrade
sudo apt install nodejs
sudo apt install  npm
sudo npm install -g yarn
sudo apt update
sudo apt upgrade
sudo apt install -y nodejs npm
sudo npm install n -g
sudo n stable
sudo apt purge -y nodejs npm
exec $SHELL -l
sudo npm install -g create-react-app
