#!/bin/bash
ESC=$(printf '\033')

read -p "${ESC}[1;39mPress setting name: ${ESC}[m" name
mkdir ~/.config 2> /dev/null

startcolor="#aa55ff"

nameFg="#002b55"
nameBg="#bf80ff"
dirFg="#0e0e47"
dirBg="#aa55ff"
gitFg="#000080"
gitBg="#952bff"
pgFg="#769ff0"
pgBg="#6a00d5"
timeFg="#a0a9cb"
timeBg="#400080"

echo "
format = \"\"\"
[░▒▓]($startcolor)\
[ $name ](bg:$nameBg fg:$nameFg)\
[](bg:$dirBg fg:$nameBg)\
\$directory\
[](fg:$dirBg bg:$gitBg)\
\$git_branch\
\$git_status\
[](fg:$gitBg bg:$pgBg)\
\$python\
\$nodejs\
\$rust\
\$golang\
\$php\
\$java\
\$kotlin\
[](fg:$pgBg bg:$timeBg)\
\$time\
[](fg:$timeBg)\
\\n\$character\"\"\"

[directory]
style = \"fg:$dirFg bg:$dirBg\"
format = \"[ \$path ](\$style)\"
truncation_length = 3
truncation_symbol = \"…/\"

[directory.substitutions]
\"Documents\" = \" \"
\"Downloads\" = \" \"
\"Music\" = \" \"
\"Pictures\" = \" \"

[git_branch]
symbol = \"\"
style = \"bg:$gitBg\"
format = '[[ \$symbol \$branch ](fg:$gitFg bg:$gitBg)](\$style)'

[git_status]
style = \"bg:$gitBg\"
format = '[[(\$all_status\$ahead_behind )](fg:$gitFg bg:$gitBg)](\$style)'

[kotlin]
symbol = \"𝕂\"
style = \"bg:$pgBg\"
format = '[[ \$symbol (\$version) ](fg:$pgFg bg:$pgBg)](\$style)'

[nodejs]
symbol = \"\"
style = \"bg:$pgBg\"
format = '[[ \$symbol (\$version) ](fg:$pgFg bg:$pgBg)](\$style)'

[java]
symbol = \"\"
style = \"bg:$pgBg\"
format = '[[ \$symbol (\$version) ](fg:$pgFg bg:$pgBg)](\$style)'

[rust]
symbol = \"\"
style = \"bg:$pgBg\"
format = '[[ \$symbol (\$version) ](fg:$pgFg bg:$pgBg)](\$style)'

[golang]
symbol = \"ﳑ\"
style = \"bg:$pgBg\"
format = '[[\$symbol (\$version) ](fg:$pgFg bg:$pgBg)](\$style)'

[php]
symbol = \"\"
style = \"bg:$pgBg\"
format = '[[\$symbol(\$version) ](fg:$pgFg bg:$pgBg)](\$style)'


[python]
symbol = \"  \"
style = \"bg:$pgBg\"
format = '[[\$symbol(\$version) ](fg:$pgFg bg:$pgBg)](\$style)'

[time]
disabled = false
time_format = \"%R\" # Hour:Minute Format
style = \"bg:#1d2230\"
format = '[[  \$time ](fg:$timeFg bg:$timeBg)](\$style)'

" > ~/.config/starship.toml
