#!/bin/bash
ESC=$(printf '\033')

read -p "${ESC}[1;39mPress setting name: ${ESC}[m" name

echo "
format = \"\"\"
[░▒▓](#a3aed2)\
[ $name ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
\$directory\
[](fg:#769ff0 bg:#394260)\
\$git_branch\
\$git_status\
[](fg:#394260 bg:#212736)\
\$python\
\$nodejs\
\$rust\
\$golang\
\$php\
\$java\
\$kotlin\
[](fg:#212736 bg:#1d2230)\
\$time\
[](fg:#1d2230)\
\\n\$character\"\"\"

[directory]
style = \"fg:#e3e5e5 bg:#769ff0\"
format = \"[ \$path ](\$style)\"
truncation_length = 3
truncation_symbol = \"…/\"

[directory.substitutions]
\"Documents\" = \" \"
\"Downloads\" = \" \"
\"Music\" = \" \"
\"Pictures\" = \" \"

[git_branch]
symbol = \"\"
style = \"bg:#394260\"
format = '[[ \$symbol \$branch ](fg:#769ff0 bg:#394260)](\$style)'

[git_status]
style = \"bg:#394260\"
format = '[[(\$all_status\$ahead_behind )](fg:#769ff0 bg:#394260)](\$style)'

[kotlin]
symbol = \"𝕂\"
style = \"bg:#212736\"
format = '[[ \$symbol (\$version) ](fg:#769ff0 bg:#212736)](\$style)'

[nodejs]
symbol = \"\"
style = \"bg:#212736\"
format = '[[ \$symbol (\$version) ](fg:#769ff0 bg:#212736)](\$style)'

[java]
symbol = \"\"
style = \"bg:#212736\"
format = '[[ \$symbol (\$version) ](fg:#769ff0 bg:#212736)](\$style)'

[rust]
symbol = \"\"
style = \"bg:#212736\"
format = '[[ \$symbol (\$version) ](fg:#769ff0 bg:#212736)](\$style)'

[golang]
symbol = \"ﳑ\"
style = \"bg:#212736\"
format = '[[\$symbol (\$version) ](fg:#769ff0 bg:#212736)](\$style)'

[php]
symbol = \"\"
style = \"bg:#212736\"
format = '[[\$symbol(\$version) ](fg:#769ff0 bg:#212736)](\$style)'


[python]
symbol = \"  \"
style = \"bg:#212736\"
format = '[[\$symbol(\$version) ](fg:#769ff0 bg:#212736)](\$style)'

[time]
disabled = false
time_format = \"%R\" # Hour:Minute Format
style = \"bg:#1d2230\"
format = '[[  \$time ](fg:#a0a9cb bg:#1d2230)](\$style)'

" > ~/.config/starship.toml
